# Generated by Django 5.2.11 on 2026-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='consultant',
            field=models.CharField(choices=[('business', 'Бизнес-консультант'), ('legal', 'Юридический консультант')], default='business', max_length=20),
        ),
    ]
